# Generated by Django 3.1.6 on 2021-08-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehtava', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiqua',
            name='arrived',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
