# Generated by Django 3.1.6 on 2021-08-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehtava', '0002_antiqua_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiqua',
            name='healtCare',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='antiqua',
            name='injections',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='antiqua',
            name='personName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
